### ISSUE TITLE
\ \\ \\\ \\\\ not honored

### ISSUE THREAD

**Issue by cristianvasquez** [syntax-tree/mdast-util-from-markdown#10]
Hello, thanks for mdast-util-from-markdown,

My report:

Say we have the following markdown file, `example.md`:
```markdown
\ \\ \\\ \\\\
```

And our script, `example.js`, looks as follows:

```js
var fs = require('fs')
var fromMarkdown = require('mdast-util-from-markdown')
var doc = fs.readFileSync('example.md')
var tree = fromMarkdown(doc)

console.log(tree.children[0].children)
```

After running, it yields:

```
  console.log
    [
      {
        type: 'text',
        value: '\\ \\ \\\\ \\\\',
        position: { start: [Object], end: [Object] }
      }
    ]
```
I would expect the values to be the same?

**Comment by wooorm** [comment]
Those are [backslash escapes](https://spec.commonmark.org/0.29/#backslash-escapes) and working as expected?

And what you see from the console log is again “escaped” by the console

**Comment by cristianvasquez** [comment]
So these are custom commonmark rules for backslash ?

Is there a way to disable these custom rules? 

I would expect to have some degree of Idempotence when applying the transform several times...

**Comment by wooorm** [comment]
It’s not a custom rule: it’s been in markdown since the beginning.
I do not suggest turning escapes off. They’re essential.
There is idempotence: just not on the first one. In html, `&semi;` also turns into `;` on the first parse/serialize, and then remains `;`.

**Comment by cristianvasquez** [comment]
I'm trying to learn the rules of escaping in markdown then. 

I experiment:
Fist time: 
\\\\\\\\\\
Second time:
\\\\\
Third time:
\\\
Fourth:
\\
Fifth:
\
I want to use this lib to arrive at a structure I can reuse many times. Maybe apply the escapes at the very end.

But there is a way to turn escapes off?

**Comment by wooorm** [comment]
That does seem like a bug, thanks, let me investigate

**Comment by wooorm** [comment]
You can use this lib to parse markdown. I’m not sure what you’re doing to serialize it, but it’s working in the companion package: https://github.com/syntax-tree/mdast-util-to-markdown/commit/e951290cc49e1a3849321073aa2dde19607d54ac

**Comment by cristianvasquez** [comment]
Thanks very much for your suggestion. 

But I'm looking for something that allows me to go from:

Markdown --to--> Tree

and then 

Tree --to--> Markdown

Without losing information, my specific use case it's to 'prettify' markdown. Like prettier does: [example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAJOBDAJnATgHSgF4TTD8KKpKbqbb7G7H7qoB9AGQggGsAadgAJIOIQCMANhDC8AzkIy44QgGYRcAWwwx4WIQCoYPAIQHyUAAbWhAKzmFVAVyhgYAS2hD3OWO5gAngAUAB4AlELAQsowTrhQQiFCAL6E1pYWAAru0jAAPgCC7rgADhr5qBBxDlAAtLV5SPVIec2EAFIQABYJACIQcHkAygDSAOJ5AIwAzNMAHB0YUCoASgN57QBiI3nTkwAsFrVCx6cn52eXFxcWANRCnO5yMIRC9wDu-l2KQgDaku4oLwALpCIIAemM4LkEE0cHeXTwcDChHuS30vyWEBgiNwQmgcGBFlefyxOLw+OWwKQQiEXV0JSQ4PBcBCGE0JUkcAAdJBNEIAOQAUTZHK5Qg8MC5Aos3GU-PcJTkTn5WAg0jxcn8ijhMH4ImgcjgbjgsTx2EVTzAgIA5kI4ACYNzCABhOIYcT+OIGqBGk1moTaELuTROBS4J5h-VG-RBkNhiUOyQJjyuHwuGD2p0gfggCAlDyG5CgJS4CDvTJKBByZAgDCSd4YAI13PiXAYWSmoYlDu25AwXBOOC5uCacRwLA4LCcJY2pwYG1wTYabS6PsoDBOYw5kD0zSSADqXX8cDkPbAcCG1f87gAbv4ArWwHIWyBAUbcDBMu2bdpkKp6yNXN7BCAAhdtOxgIZ2TgR5ln-QDhxAEChltLkAEUnGxOAEMkICQB7XAP1rbRcF4NV3igHcSgjWADx8HFkDmAAGXMaIgI0D3bEpaxo088FvHDcwARyw+Bv3zGsNzkWplgnCcd2UUTijgb8Fz-JAALwpCjU0dx+0HHS0LgTDsNw-CYA9eisEYpAACZcwHDAcltF1YQ0kBTwAVh3MM4AAFQ9KStPw28hwASSgXwoLACMCwKKKhkCLlzLgZJkiAA)

**Comment by wooorm** [comment]
Markdown -> tree and tree -> markdown is exactly what these two projects do.
And you want to lose information in order to format nicely: you don’t care about whether someone used asterisks for or underscores for emphasis. Prettier is also built on these tools.

Anyway, your question here is on a project that parses markdown and it does so according to the spec. If you want to format markdown, you have the tree to do with whatever you please.

**Comment by cristianvasquez** [comment]
Thanks, @wooorm. I'm not criticizing or anything I'm very grateful for these tools,

I'm just trying to understand the rationale behind not including escapes as part of the Tree. Until now I thought that all escapes were useful for serializing into specific output formats, being HTML just a special case. 

I'll look into how prettier does it. 

Again thanks

**Comment by wooorm** [comment]
The reason for excluding such information is because of the difference between an AST and a CST: https://github.com/syntax-tree/unist#syntax-tree.

Typically, you care about what the document means, not how exactly it was written. In fact, if you‘re prettifying then it’s pretty nice because you don’t have to remove useless escapes: that superfluous information isn’t in the tree to begin with. Similar to how it’s not added whether double or single quotes were used in a title (`[link](url "title")`).

This parser is made on micromark, and micromark *does* have all the information for you to make a CST with, but I haven’t gotten around to it yet. https://github.com/micromark/micromark

**Comment by pngwn** [comment]
Hey, I have a similar issue to this one (relating to backslash escapes) but inside code blocks:

````md
```
RUN bash -lc "rvm install ruby-2.5.1 && \
              rvm use ruby-ruby-2.5.1 --default"
```
```` 

If i add a space after the `\` or another `\` before it it works fine but otherwise both the backslash and the newline are removed. I'm actually using `remark-parse` 8.0.3 but this issue is also present in `9.x` (although I am not able to update to that yet).

Is this expected and is it the same issue? Or am I doing something wrong?

**Comment by wooorm** [comment]
With the following code:

```js
var fs = require('fs')
var unified = require('unified')
var remarkParse = require('remark-parse')

console.log(
  unified()
    .use(remarkParse)
    .parse(fs.readFileSync('example.md')).children[0]
)
```

And these dependencies:

```
$ npm ls
example-1@1.0.0 /Users/tilde/Projects/oss/example-1
├── remark-parse@9.0.0
└── unified@9.2.1
```

And this markdown:

````markdown
```
a \
b
```
````

Yields:

```js
{
  type: 'code',
  lang: null,
  meta: null,
  value: 'a \\\nb',
  position: {
    start: { line: 1, column: 1, offset: 0 },
    end: { line: 4, column: 4, offset: 13 }
  }
}
```

(a, space, slash, line feed, b).

Adding a space after the slash yields:

```js
{
  type: 'code',
  lang: null,
  meta: null,
  value: 'a \\ \nb',
  position: {
    start: { line: 1, column: 1, offset: 0 },
    end: { line: 4, column: 4, offset: 14 }
  }
}
```

(a, space, slash, space, line feed, b).

Going back to the first reduced case, but using two slashes yields:

```js
{
  type: 'code',
  lang: null,
  meta: null,
  value: 'a \\\\\nb',
  position: {
    start: { line: 1, column: 1, offset: 0 },
    end: { line: 4, column: 4, offset: 14 }
  }
}
```

(a, space, slash, slash, space, line feed, b).

---

Trying the same examples out on remark-parse@8.0.3, also gives me the same results.
That is to say, I cannot reproduce your problem.
And it doesn’t seem like something remark would do: you are giving it code, escapes in code are not handled at all.
If I had to guess, mdsvex is probably somewhere escaping stuff svelte compiler, in which case, it might be a bug there?

**Comment by wooorm** [comment]
Alternatively, if this isn’t about code (which seems weird, because in the linked issue the text is set in monospace and the whitespace shows up as pre-formatted), these are [hard line breaks](https://spec.commonmark.org/0.29/#hard-line-break)

**Comment by pngwn** [comment]
I assumed it was something in mdsvex but the newline and slash are stripped before any of the mdsvex plugins get to see it. Which is why i dug into this a bit more.

It looks like `\\n` is just being escaped by virtue of it being loaded into memory. Since mdsvex doesn't load a file but have a string variable that is passed to remark-parse, the escapes have already been applied.

If you change your example to this i think you will see what I am seeing:

```js
var fs = require('fs')
var unified = require('unified')
var remarkParse = require('remark-parse')

const src = `
\`\`\`
a \
b
\`\`\`
`;

console.log(
  unified()
    .use(remarkParse)
    .parse(src).children[0]
)
```

But this has nothing to do with remark-parse. I'm not sure what the best solution is here, I may be able to use a tagged template literal to pull out the raw value as early as possible but i don't know if that will work in every case

**Comment by pngwn** [comment]
So, this is because it is a template literal as far as I'm aware. 

Thanks for responding and apologies for the noise.

**Comment by wooorm** [comment]
> So, this is because it is a template literal as far as I'm aware.

This is the same for normal strings:

```
a = 'b\
c\
d'
=> 'bcd'
```

So, it’s essentially a way to have long strings broken over several lines for readability.

But, why is a literal string (as written in a JS file), instead of an actual string (coming from a file) being passed to remark? That still sounds weird... Are you parsing MDsveX as JS first, and *then* as markdown?

**Comment by pngwn** [comment]
Well this is a preprocessor for svelte in most cases. So the source file goes through `rollup` (or another bundler) -> `svelte` -> `mdsvex`. There isn't much parsing going on in those cases but that is the rough flow.

I need to check whether what I'm seeing is just a limitation of my tests though, I'm seeing this behaviour in tests and simple repro's, I need to validate this behaviour in a more realistic setup.

**Comment by pngwn** [comment]
Apologies for wasting your time here, I can't even reproduce the problem in the linked issue. Probably something else going on.

**Comment by cristianvasquez** [comment]
> The reason for excluding such information is because of the difference between an AST and a CST: https://github.com/syntax-tree/unist#syntax-tree.
> 
> Typically, you care about what the document means, not how exactly it was written. In fact, if you‘re prettifying then it’s pretty nice because you don’t have to remove useless escapes: that superfluous information isn’t in the tree to begin with. Similar to how it’s not added whether double or single quotes were used in a title (`[link](url "title")`).
> 
> This parser is made on micromark, and micromark _does_ have all the information for you to make a CST with, but I haven’t gotten around to it yet. https://github.com/micromark/micromark

The only problem I have is that users sometimes try to intentionally wite \# or \| because they want the character to be interpreted as it is. For example,  write \* to be interpreted as plaintext *, instead of emphasis. When I run this library, \| is transformed into |
.

**Comment by wooorm** [comment]
This project is doing what markdown dictates: parsing markdown according to the spec(s). The rest of the pipeline also seems to behave correctly. Your prose is what is being done. Can you provide a codesandbox of what isn't working?

**Comment by cristianvasquez** [comment]
I cannot find the Issue in GitHub anymore

I have this sandbox

https://codesandbox.io/s/remark-commented-chars-9dzx5?file=/src/index.js

I don't get why some chars \| and \# behave differently

**Comment by wooorm** [comment]
This is about two tings: a) parsing, b) formatting.
For parsing, ASCII punctuation is all parsed the same.
For formatting, the hash could result in a heading, the pipe can’t (in CommonMark) result into something. So the first needs to be escaped again, the other one doesn’t.

**Comment by cristianvasquez** [comment]
Thanks for your response!
