### ISSUE TITLE
Nested ordered lists

### ISSUE THREAD

**Issue by pcaselas** [syntax-tree/mdast-util-from-markdown#33]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.0.0 (but I've tried 1.3.5 and 0.8.5 and have the same problem)

### Link to runnable example

https://codesandbox.io/s/sharp-wing-skflm6?file=/src/index.ts

### Steps to reproduce

const content = `
1. **Test 1**
   1. Test 1.1
2. **Test 2**
   1. Test 2.1
3. **Test 3**
   1. Test 3.1
4. **Test 4**
   1. Test 4.1
5. **Test 5**
   1. Test 5.1
6. **Test 6**
   1. Test 6.1
7. **Test 7**
   1. Test 7.1
8. **Test 8**
   1. Test 8.1
9. **Test 9**
   1. Test 9.1
10. **Test 10**
   1. Test 10.1
11. **Test 11**
   1. Test 11.1
12. **Test 12**
   1. Test 12.1
13. **Test 13**
   1. Test 13.1
14. **Test 14**
   1. Test 14.1
15. **Test 15**
   1. Test 15.1
`
import { serve } from "https://deno.land/std@0.91.0/http/server.ts";
import { fromMarkdown } from "https://esm.sh/mdast-util-from-markdown@2";
const s = serve({ port: 8080 });

console.log("http://localhost:8080/");

for await (const req of s) {
  const parsed = fromMarkdown(content);
  const stringified = JSON.stringify(parsed, 0, 2);
  req.respond({ body: stringified });
}

### Expected behavior

From 10 and afterwards is still a nested list.

### Actual behavior

from 10 and afterwards is not parsed like a nested list.

### Affected runtime and version

deno@latest in this sample but node 18 on my local machine

**Comment by pcaselas** [comment]
Apparently even the markdown parser from github gets it wrong. Is it using mdast? 🤔

**Comment by ChristianMurphy** [comment]
Welcome @pcaselas! 👋 
What you are describing is how markdown lists work.
The full behavior is documented in the spec https://spec.commonmark.org/0.30/#list-items
The short version is the marker for nested lists need to be beyond the `. ` of the parent list to nest properly.

An example which would be valid

```md
1. **Test 1**
    1. Test 1.1
2. **Test 2**
    1. Test 2.1
3. **Test 3**
    1. Test 3.1
4. **Test 4**
    1. Test 4.1
5. **Test 5**
    1. Test 5.1
6. **Test 6**
    1. Test 6.1
7. **Test 7**
    1. Test 7.1
8. **Test 8**
    1. Test 8.1
9. **Test 9**
    1. Test 9.1
10. **Test 10**
    1. Test 10.1
11. **Test 11**
    1. Test 11.1
12. **Test 12**
    1. Test 12.1
13. **Test 13**
    1. Test 13.1
14. **Test 14**
    1. Test 14.1
15. **Test 15**
    1. Test 15.1
```

which renders as:

---

1. **Test 1**
    1. Test 1.1
2. **Test 2**
    1. Test 2.1
3. **Test 3**
    1. Test 3.1
4. **Test 4**
    1. Test 4.1
5. **Test 5**
    1. Test 5.1
6. **Test 6**
    1. Test 6.1
7. **Test 7**
    1. Test 7.1
8. **Test 8**
    1. Test 8.1
9. **Test 9**
    1. Test 9.1
10. **Test 10**
    1. Test 10.1
11. **Test 11**
    1. Test 11.1
12. **Test 12**
    1. Test 12.1
13. **Test 13**
    1. Test 13.1
14. **Test 14**
    1. Test 14.1
15. **Test 15**
    1. Test 15.1

---

To simplify validating that your nested markdown lists are correct.
Consider using https://github.com/remarkjs/remark-lint/tree/main/packages/remark-preset-lint-recommended which offers guidance on adding spacing so that nesting will work properly.
